In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Project Finance.xlsx to Project Finance.xlsx

In [ ]:
df = pd.read_excel('Project Finance.xlsx', sheet_name='Forecasting')
df.head()

  Forecasting  Monthly Revenue
0  2013-09-01     6.117184e+06
1  2013-10-01     1.118875e+07
2  2013-11-01     7.630027e+06
3  2013-12-01     6.497387e+06
4  2014-01-01     8.236148e+06

In [ ]:
df.dtypes

Forecasting        datetime64[ns]
Monthly Revenue           float64
dtype: object

In [ ]:
from statsmodels.tsa.holtwinters import Holt

In [ ]:
df['Forecasting'] = pd.to_datetime(df['Forecasting'])
df.set_index('Forecasting', inplace=True)

In [ ]:
df.head()

             Monthly Revenue
Forecasting
2013-09-01      6.117184e+06
2013-10-01      1.118875e+07
2013-11-01      7.630027e+06
2013-12-01      6.497387e+06
2014-01-01      8.236148e+06

In [ ]:
df.dtypes

Monthly Revenue    float64
dtype: object

In [ ]:
df.index.freq = 'MS'

In [ ]:
df.dtypes

Monthly Revenue    float64
dtype: object

In [ ]:
series_data = df['Monthly Revenue']

In [ ]:
model = Holt(series_data, exponential=False, initialization_method='estimated')
fit_model = model.fit(optimized=True)

In [ ]:
forecast_steps = 12
forecast = fit_model.forecast(steps=forecast_steps)

In [ ]:
print(forecast)

2015-01-01    9.740952e+06
2015-02-01    9.902092e+06
2015-03-01    1.006323e+07
2015-04-01    1.022437e+07
2015-05-01    1.038551e+07
2015-06-01    1.054665e+07
2015-07-01    1.070779e+07
2015-08-01    1.086893e+07
2015-09-01    1.103007e+07
2015-10-01    1.119121e+07
2015-11-01    1.135235e+07
2015-12-01    1.151349e+07
Freq: MS, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

In [ ]:
train_data = series_data.iloc[:-12]
test_data = series_data.iloc[-12:]

In [ ]:
model = Holt(train_data, exponential=False, initialization_method='estimated')
fit_model = model.fit(optimized=True)

In [ ]:
predictions = fit_model.forecast(len(test_data))

In [ ]:
rmse = np.sqrt(mean_squared_error(test_data, predictions))
mape = mean_absolute_percentage_error(test_data, predictions) * 100

In [ ]:
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

Root Mean Squared Error (RMSE): 2300512.61
Mean Absolute Percentage Error (MAPE): 21.90%